### ISSUE TITLE
Saving and Publishing a page, containing the OP10 Multiple Media Picker, resets the Crop focus point on the picked images when the Image Cropper is used as the umbracoFile property and Quick View Properties are selected

### ISSUE THREAD

**Issue by marcemarc** [OPTEN/OP10-Multiple-Media-Picker#1]
To replicate
Set the umbracoFile property on the default media type to be Image Cropper
Upload an image
Set the focus point off centre
Pick the image with the OP10 Multiple Media Picker on a page
Save and Publish page
Focus point is reset to be the centre of the image
but only if quick view properties are ticked
if you untick the properties and only save your media changes from the slide out window, crop focus position is maintained...

**Comment by AaronMorf** [comment]
Sorry for being late in fixing this bug

**Comment by marcemarc** [comment]
Thanks @AaronMorf it's a great package core-worthy!
