### ISSUE TITLE
Compatibility issue with new version 1.3.3 and Umbraco 7.3.8?

### ISSUE THREAD

**Issue by Nora0707** [OPTEN/OP10-Multiple-Media-Picker#15]
Today I updated the OP10 Multiple Media Picker in a 7.3.8 installation and was not able to get the media ID any more. All I got was 

**Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache+DictionaryPublishedContent** 
  
I downgraded again to version 1.3.1 and everything worked properly just like before. Just wanted to let you know. Or is there a new way to output the media ID with the new version? 

Thanks a lot for your great work with this plugin :)

**Comment by Nora0707** [comment]
And one more little thing - in Version 7.3.8 of Umbraco with the plugin Version 1.3.1 there is a little bug related to the focal point for the image cropper - its positioned relative and so it's not visible in the dialog and the quick-edit view. Adding this style fixed the issue for me: 
.umb-cropper-gravity .overlay {
	position:absolute !important;
}
(Didn't notice any side effects so far, but it's just tested in one installation). 
Regards, 
Nora

**Comment by AaronMorf** [comment]
You can use it now with the ModelsBuilder to get directly a media object instead of only the id.
Or use it like GetPropertyValue<IPublishedContent>("alias")

It now does work without the extra css styles. Hope it works for you too!
