### ISSUE TITLE
Link to open media in new window

### ISSUE THREAD

**Issue by akeilox** [OPTEN/OP10-Multiple-Media-Picker#7]
Thank you for this neat package.

I am using it to select image and pdf files on a content node, and wondering whats the best way to add click-to-open in new page button (perhaps before the Gear settings icon).
If image is screenshot or media is of PDF editors would like to be able to click to open the file on new window.

I looked at the multipleMediaPicker.html to see if extra button before settings-icon can be added, but not sure how to get the direct file url injected in angular.

**Comment by AaronMorf** [comment]
Thank you for your Feedback.
You are now able to select the property "Link to media" inside the DataType to show an icon linked to the media.

**Comment by akeilox** [comment]
Many thanks for the update. Works great!
