### ISSUE TITLE
Image description unavailable

### ISSUE THREAD

**Issue by ghetal** [OPTEN/OP10-Multiple-Media-Picker#8]
Hey, I have installed the latest version of OP10-Multiple-Media-Picker. But Can't see the Image description checkbox while creating the datatype. can you help?

![image](https://cloud.githubusercontent.com/assets/25324185/22250370/a5ac3104-e26c-11e6-8d44-609c2423587e.png)

**Comment by AaronMorf** [comment]
You first need to create a property for the Image located in the "Settings" section "Media Types". There you can add a property, which is then listed in the OP10-Multiple-Media-Picker.
![unbenannt](https://cloud.githubusercontent.com/assets/10773071/22322467/8dd84d52-e39c-11e6-87e5-f482974e3bd3.PNG)

**Comment by ghetal** [comment]
Thank you. It solved the issue. But in that case original 'Image' media type is to be changed, so that is a bit unacceptable.

**Comment by AaronMorf** [comment]
We have been discussing this in our team and we came to the concluion, that it is not unacceptable. This is a simple extension to edit any properties in the Content section. What would be your solution to not add it at the Image Media Type?

**Comment by ghetal** [comment]
You are right. But, if we can make custom image type by copying the original image type and then allow user to use this with added properties, then it will better. As original image type with its properties will remain unchanged,

**Comment by AaronMorf** [comment]
In a next version I try to provide a "Media Type Alias" selector that you can define what types should be used.
![pasted_image_at_2017_01_26_09_44_am](https://cloud.githubusercontent.com/assets/10773071/23500088/fadbd7ea-ff2e-11e6-81ac-c52a0611fbd9.png)
